### ISSUE TITLE
Update the Emogrifier dependency to ^2.0.0

### ISSUE THREAD

**Issue by oliverklee** [hnhdigital-os/laravel-emogrifier#2]
Emogrifier 2.0.0 has been released, providing lots of bug fixes and PHP 7.2 compatibility. I propose upgrading to that version (if you don't need to support PHP 5.4).

**Comment by RoccoHoward** [comment]
Thanks. Sounds good. I'll flick it up.

**Comment by RoccoHoward** [comment]
* Changed version 1 code to the `v1` branch. Created a `v1` release.
* Updated master and code to `v2` and created a `v2` release.

**Comment by oliverklee** [comment]
Thanks! ❤️
